### ISSUE TITLE
Screenshot is not properly shown in the website

### ISSUE THREAD

**Issue by jgarciao** [flathub/org.kde.kontact#1]
The screenshot for this app is not shown correctly in the webapp: https://flathub.org/apps/details/org.kde.kontact

If you check the apptream file in your computer (/var/lib/flatpak/appstream/flathub/x86_64/active/appstream.xml) this is the screenshot info for your app: 
```
<screenshots>
   <screenshot type="default">
      <image type="source">http://kde.org/images/screenshots/kontact.png</image>
      <image type="thumbnail" height="351" width="624">https://flathub.org/repo/screenshots/org.kde.kontact-stable/624x351/org.kde.kontact-2a4c498ab1c9d2aa40aaa0c47e4825d4.png</image>
      <image type="thumbnail" height="702" width="1248">https://flathub.org/repo/screenshots/org.kde.kontact-stable/1248x702/org.kde.kontact-2a4c498ab1c9d2aa40aaa0c47e4825d4.png</image>
      <image type="thumbnail" height="63" width="112">https://flathub.org/repo/screenshots/org.kde.kontact-stable/112x63/org.kde.kontact-2a4c498ab1c9d2aa40aaa0c47e4825d4.png</image>
      <image type="thumbnail" height="126" width="224">https://flathub.org/repo/screenshots/org.kde.kontact-stable/224x126/org.kde.kontact-2a4c498ab1c9d2aa40aaa0c47e4825d4.png</image>
      <image type="thumbnail" height="423" width="752">https://flathub.org/repo/screenshots/org.kde.kontact-stable/752x423/org.kde.kontact-2a4c498ab1c9d2aa40aaa0c47e4825d4.png</image>
   </screenshot>
</screenshots>
```

The [source image](http://kde.org/images/screenshots/kontact.png) looks fine but the thumbnail ones (which are the ones used in the website) [look empty](https://flathub.org/repo/screenshots/org.kde.kontact-stable/624x351/org.kde.kontact-2a4c498ab1c9d2aa40aaa0c47e4825d4.png)

I've seen a similar problem in the past and the solution was to use  a source image that has 16:9. See [this issue](https://github.com/flathub/de.wolfvollprecht.UberWriter/issues/2) for more info.

**Comment by danvratil** [comment]
Thanks, I updated the appdata file (also in upstream) to include new fancy screenshots and to make sure they have the right size.

**Comment by jgarciao** [comment]
Thanks!
