### ISSUE TITLE
Should akonadiconsole be available in the flatpak?

### ISSUE THREAD

**Issue by detrout** [flathub/org.kde.kontact#14]
When trying to debug a problem where I was getting 100% cpu usage in one of the imap transfer components I went looking for akonadiconsole to try and see what was going on, and I couldn't find it.

Seems like another thing that could be added to the flatpak.

**Comment by danvratil** [comment]
Good point - although we would probably need to add some special menu action to KMail to launch it. I don't think it's possible to launch another process inside of the same sandbox from the outside.

**Comment by danvratil** [comment]
Added to the 18.12.2 update.

**Comment by qwertyuser1983** [comment]
> Added to the 18.12.2 update.

Is the FlatPak Kontact has been updated yet?

**Comment by danvratil** [comment]
Sorry, there were some issues with the Flathub builds. The 18.12.2 update should be available today.

**Comment by danvratil** [comment]
Sorry, more build issues :( I'll try to sort it out over the weekend.
