### ISSUE TITLE
pimsettingsexporter is not available

### ISSUE THREAD

**Issue by VosaXalo** [flathub/org.kde.kontact#16]
I was trying to import my kmail settings, but the tool **pimsettingsexporter** is not available. When you select the mail tab in kontact, then you open the Tools menu, you have the option to "Import/Export Kmail data", but the pimsettingsexporter doesn't start.

During the installation of the ftatpak, the tool is listed between others in the following list, but despite this, it's not available:
**dbus ownership**: org.freedesktop.Akonadi, org.freedesktop.Akonadi.*, org.freedesktop.Akonadi.Agent.*, org.freedesktop.Akonadi.Control.*, org.freedesktop.Akonadi.Resource.*, org.kde.accountwizard, org.kde.akregator, org.kde.kaddressbook, org.kde.kalarm, org.kde.kmail, org.kde.kmail2, org.kde.knotes, org.kde.kontact, org.kde.korgac, org.kde.korganizer, org.kde.pim.*, **org.kde.pimsettingsexporter**, org.kde.sieveeditor

**Comment by danvratil** [comment]
Fixed in the 18.12.2 update, the program is actually there but there was a typo in the list of DBus interfaces.
