### ISSUE TITLE
When adding a DAV groupware resource with self signed certificate, dialog shows up under dialogs

### ISSUE THREAD

**Issue by BeatLink** [flathub/org.kde.kontact#179]
Ive experienced this bug with both kontact and calendar. When attempting to add a dav groupware resource that has a self signed certificate, an error dialog shows up but its under all of the other credentials forms, preventing you from acknowledging the self signed certificate and continuing to add the resource.

**Comment by BeatLink** [comment]
Update, it happens whenever any message shows up from the groupware adding dialog where you configure the resource manually

**Comment by tsdgeos** [comment]
This doesn't seem like a flathub packaging problem i would suggest reporting it on https://bugs.kde.org
