### ISSUE TITLE
Add YAML support to tools/update.py

### ISSUE THREAD

**Issue by eszlari** [flathub/org.kde.kontact#21]
This script is very handy and it would be nice, if you could add support for updating YAML manifests.

**Comment by eszlari** [comment]
I also noticed, that this script doesn't work, when the manifest contains submodule, e.g.:

https://github.com/flathub/org.kde.ksudoku/blob/master/org.kde.ksudoku.json

```
Traceback (most recent call last):
  File "./update.py", line 89, in <module>
    main()
  File "./update.py", line 82, in main
    update_modules(args, j['modules'])
  File "./update.py", line 62, in update_modules
    sources = module['sources']
TypeError: string indices must be integers

```

**Comment by danvratil** [comment]
Do you have an example of a KDE flatpak that uses YAML manifest instead of JSON?

**Comment by eszlari** [comment]
https://github.com/flathub/org.kde.okular
https://github.com/flathub/org.kde.kdenlive

**Comment by danvratil** [comment]
YAML support added in commit fc9c96d.
