### ISSUE TITLE
Kontact fails to start

### ISSUE THREAD

**Issue by andrevmatos** [flathub/org.kde.kontact#221]
Since a couple of days ago, my Kontact can't launch anymore. Maybe #220?
I'm pretty sure that I saw the v6 running for some time, then it stopped.
Running from terminal just shows:
```
kbuildsycoca6 running...
"applications.menu"  not found in  QList()
```
Then quits with some KILL return code.

NixOS plasma6 wayland session.

**Comment by travier** [comment]
It runs for me here so this is likely not the error and something else is missing maybe on your system.

**Comment by andrevmatos** [comment]
Looks like the situation improved in latest org.kde.Platform updates. Working fine here again. Thank you
