### ISSUE TITLE
Should the flatpak be able to talk to org.kde.kpasswdserver?

### ISSUE THREAD

**Issue by detrout** [flathub/org.kde.kontact#30]
I was periodically getting this error message when starting akonadi in the container manually

```
kf5.kio.core: Can't communicate with kiod_kpasswdserver (for checkAuthInfo)!
kf5.kio.core: Can't communicate with kiod_kpasswdserver (for checkAuthInfo)!
```
I found the relevant dbus name is
```
        "--talk-name=org.kde.kpasswdserver",
```

And it looks like this is the current API docs for the checkAuthInfo call
https://api.kde.org/frameworks/kio/html/classKPasswdServerClient.html

I'm guessing its a password caching API for kio workers?

**Comment by danvratil** [comment]
Fixed in #32.
