### ISSUE TITLE
update to 20.04

### ISSUE THREAD

**Issue by eszlari** [flathub/org.kde.kontact#33]

**Comment by eszlari** [comment]
@danvratil are you still maintaining this flatpak?

**Comment by cho2** [comment]
Trying to update to the latest version (20.04.3) https://github.com/flathub/org.kde.kontact/pull/39 still error

**Comment by eszlari** [comment]
fixed: https://github.com/flathub/org.kde.kontact/commit/b81f4589ee795fb692547d9d9093aebb2051433a
