### ISSUE TITLE
Cannot connect to nextcloud calendars (Incompatible version of OpenSSL on Ubuntu 22.04)

### ISSUE THREAD

**Issue by DrAxelbauer** [flathub/org.kde.kontact#71]
Hi there!
I installed kontact via flatpak and tried to connect to my nextcloud calendars. Testing the connections won't work and so the calenders are not added & synced with my server. Any suggestions where to start?

STEPS TO REPRODUCE
1. Add a DAV-Groupware calender (nextcloud)
2. Testing the connections
3. Error:  Es ist ein Fehler aufgetreten: Bei der Abfrage ist ein Problem aufgetreten HTTP-Fehler (0).

OBSERVED RESULT
No calender added or synced

EXPECTED RESULT
Sync my nextcloud calendars

```
I just saw that the problem might have to do with akonadi & openssl ... versions incompatible:
qt.network.ssl: Incompatible version of OpenSSL
qt.network.ssl: QSslSocket::startClientEncryption: TLS initialization failed
qt.network.ssl: QSslSocket::startClientEncryption: TLS initialization failed
org.kde.pim.davresource: Unable to fetch collections 300 "Bei der Abfrage ist ein Problem aufgetreten\nHTTP-Fehler (0)."
qt.network.ssl: QSslSocket::startClientEncryption: TLS initialization failed
qt.network.ssl: QSslSocket::startClientEncryption: TLS initialization failed
org.kde.pim.davresource: Unable to fetch collections 300 "Bei der Abfrage ist ein Problem aufgetreten\nHTTP-Fehler (0)."
```

SOFTWARE/OS VERSIONS
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.93.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-25-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-8565U CPU @ 1.80GHz
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620

**Comment by Victor239** [comment]
I don't think this is a Flatpak-specific issue, you'll want to file a bug on Kontact's [main repo here](https://bugs.kde.org/describecomponents.cgi?product=kontact).

**Comment by DrAxelbauer** [comment]
...seems that noone has an idea about the issue...
I posted the issue here, because they told my i should try it here...
See
https://bugs.kde.org/show_bug.cgi?id=453121

**Comment by DrAxelbauer** [comment]
Mhm interesting it seems to be the only case I came across this. 
Server runs on 20.04 and my system is on 22.04. But as far as I could remember, the bug also existed when running the system on 20.04.
NC is fully updated...

**Comment by DrAxelbauer** [comment]
Okay I tried to upgrade openssl on the server to the same in ubuntu 22.02 (OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022) but without success still the same error. 
So I guess it is a bug in akonadi or kontact itself...

**Comment by Victor239** [comment]
Related case where Lutris can no longer login to EA because of Ubuntu using newer SSL https://github.com/lutris/lutris/issues/4235

Yeah your best bet is to try the issue in the non-Flatpak version and report your findings to the bug tracker

**Comment by DrAxelbauer** [comment]
Okay i had success while running through this issue:
https://stackoverflow.com/questions/52210603/qt-and-openssl-incompatible-version-on-ubuntu#52210604

That is definitely the problem here.

In my case the solution was easy. Just install libssl-dev:
`sudo apt install libssl-dev`
did the trick. There are some symlinks missing or incompatibilities in qt networking and openssl...
