### ISSUE TITLE
Compatibility with kdepim-runtime-etesync

### ISSUE THREAD

**Issue by Victor239** [flathub/org.kde.kontact#74]
I can use this package with non-Flatpak Kontact in order to [use EteSync as a calendar provider](https://www.etesync.com/user-guide/kontact/). Is there any way to get it working with this Flatpak version?

**Comment by tsdgeos** [comment]
We would need to compile libetebase itself, uses rust to compile, I've never done that, help welcome :)

**Comment by Victor239** [comment]
It doesn't show up for me as a calendar option still:

![](https://i.imgur.com/vRcag2l.png)

I think it may need `kdepim-runtime-etesync` compiled in addition to `libetebase`?

**Comment by tsdgeos** [comment]
Works fine for me 

![imatge](https://user-images.githubusercontent.com/9051674/170307306-defcae07-2cca-4633-9867-1c0d20e0bd63.png)

Are you sure you have run flatpak update?

What does flatpak info org.kde.kontact return?

**Comment by Victor239** [comment]
Ah, it appears now after having restarted my PC. Odd, I had already updated the Flatpak and restarted Kontact. Thanks for this!
